Sync khs1994-docker/lnmp

diff --git a/lnmp-k8s b/lnmp-k8s
--- a/lnmp-k8s
+++ b/lnmp-k8s
@@ -51,7 +51,7 @@ Kubernetes version is ${KUBERNETES_VERSION}
 Usage: lnmp-k8s COMMAND
 
 Commands:
-  kubernetes-server      Download kubernetes server files {GOOS} {GOARCH} {TYPE:-server} {KUBERNETES_VERSION:-${KUBERNETES_VERSION}}
+  kubernetes-server      Download kubernetes server files [--url ] {GOOS} {GOARCH} {TYPE:-server} {KUBERNETES_VERSION:-${KUBERNETES_VERSION}}
   pull-k8s-image         Use By developer Only {GOOS} {GOARCH} {TYPE:-server} {KUBERNETES_VERSION:-${KUBERNETES_VERSION}}
 
   kubectl-install        Install kubectl
@@ -60,11 +60,11 @@ Commands:
   minikube-install       Install minikube
   minikube               Start minikube
 
-  single-install         Install Single Kubernetes（Manager by systemd）[--containerd | ]
+  single-install         Install Single Kubernetes（Manager by systemd）[--containerd | --crio | ]
   single-start           Print how to start Single Kubernetes (Manager by systemd)
   single-cleanup         Cleanup Single Kubernetes.
 
-  join                   New worker [NODE_IP] [--containerd | ]
+  join                   New worker [NODE_IP] [--containerd | --crio | ]
 
   create                 Deploy lnmp on k8s [--ingress | --no-nfs ]
   delete                 Stop lnmp on k8s, keep data resource(pv and pvc)
@@ -82,6 +82,10 @@ Commands:
 "
 }
 
+_sudo(){
+  command -v sudo > /dev/null && echo sudo
+}
+
 case `uname -m` in
   x86_64 )
   GOARCH=amd64
@@ -95,7 +99,7 @@ esac
 
 GOOS=`uname -s | tr A-Z  a-z`
 
-_pull_k8s_image(){
+_get_kubernetes_server_by_docker_image(){
   local TYPE=server
   test -n "${1}" && local GOOS=$1
   test -n "${2}" && local GOARCH=$2
@@ -110,6 +114,7 @@ _pull_k8s_image(){
   docker container rm khs1994-kubernetes-${TYPE} > /dev/null 2>&1 || true
   docker container create --name khs1994-kubernetes-${TYPE} \
     ccr.ccs.tencentyun.com/khs1994/kubernetes-${TYPE}-${GOOS}-${GOARCH}:v${KUBERNETES_VERSION}
+  docker container ls -a --filter name=khs1994-kubernetes-${TYPE}
   docker container cp khs1994-kubernetes-${TYPE}:/kubernetes-${TYPE}-${GOOS}-${GOARCH}.tar.gz kubernetes-release/release/kubernetes-${TYPE}-${GOOS}-${GOARCH}-${KUBERNETES_VERSION}.tar.gz
   docker container rm khs1994-kubernetes-${TYPE}
 }
@@ -117,13 +122,17 @@ _pull_k8s_image(){
 _get_kubernetes_server_by_url(){
   curl https://storage.googleapis.com/kubernetes-release/release/stable.txt \
     && ( \
-       cd kubernetes-release/release/ \
-         && curl -L https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/kubernetes-server-${GOOS}-${GOARCH}.tar.gz \
-                 -o kubernetes-server-${GOOS}-${GOARCH}-${KUBERNETES_VERSION}.tar.gz \
+      curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/kubernetes-server-${GOOS}-${GOARCH}.tar.gz \
+        -o kubernetes-release/release/kubernetes-server-${GOOS}-${GOARCH}-${KUBERNETES_VERSION}.tar.gz \
     ) && return 0 || return 1
 }
 
 _kubernetes_server_install(){
+  if [ "$1" = "--url" ];then
+    local get_by_url=1
+    shift 1
+  fi
+
   test -n "${1}" && local GOOS=$1
   test -n "${2}" && local GOARCH=$2
   test -n "${3}" && local TYPE=$3
@@ -158,11 +167,19 @@ mkdir -p kubernetes-release/release/v${KUBERNETES_VERSION}-${GOOS}-${GOARCH}
 
   test $GOOS != 'linux' && exit
 
+  if [ -n "$get_by_url" ];then
+    _get_kubernetes_server_by_url $@
+    cd kubernetes-release/release
+    __untar $@
+
+    return
+  fi
+
   command -v docker > /dev/null
 
   if [ $? -eq 0 ];then
     docker container ls > /dev/null 2>&1
-    _pull_k8s_image $@
+    _get_kubernetes_server_by_docker_image $@
     cd kubernetes-release/release
     __untar $@
   fi
@@ -181,13 +198,13 @@ _minikube_up(){
   if [ `uname -s` = 'Darwin' ];then
     minikube start \
       -v 10 \
-      --registry-mirror=https://registry.docker-cn.com \
+      --registry-mirror=https://dockerhub.azk8s.cn \
       --vm-driver="hyperkit" \
       --memory=4096
   else
     minikube start \
       -v 10 \
-      --registry-mirror=https://registry.docker-cn.com \
+      --registry-mirror=https://dockerhub.azk8s.cn \
       --vm-driver="none"
   fi
 }
@@ -401,6 +418,39 @@ _helm_install(){
   sudo rm -rf /tmp/${GOOS}-${GOARCH}
 }
 
+_gvisor_docker_conf(){
+  print_info "config docker with gvisor(runsc) ..."
+  echo ""
+}
+
+_gvisor_containerd_conf(){
+  print_info "config containerd with gvisor(runsc) ..."
+  cat <<EOF | sudo tee -a /etc/containerd/config.toml
+[plugins.cri.containerd.runtimes.runsc]
+  runtime_type = "io.containerd.runsc.v1"
+EOF
+}
+
+_gvisor_crio_conf(){
+  print "config crio with gvisor(runsc) ..."
+  cat <<EOF | sudo tee -a /etc/crio/crio.conf
+[crio.runtime.runtimes.runsc]
+  runtime_path = "/usr/local/bin/runsc"
+EOF
+}
+
+_gvisor_install(){
+  print_info "install gvisor ..."
+  sudo curl -fsSL -o /usr/local/bin/containerd-shim-runsc-v1 \
+    https://github.com/google/gvisor-containerd-shim/releases/download/v0.0.3/containerd-shim-runsc-v1.linux-amd64
+  sudo chmod +x /usr/local/bin/containerd-shim-runsc-v1
+
+  sudo curl -fsSL -o /usr/local/bin/runsc \
+    https://github.com/khs1994-docker/gvisor-mirror/releases/download/nightly/runsc
+
+  sudo chmod +x /usr/local/bin/runsc
+}
+
 _cni_install(){
   sudo mkdir -p /opt/k8s/cni/bin
   if [ -f /opt/k8s/cni/bin/flannel ];then
@@ -433,10 +483,10 @@ _k8s_install_dep(){
   print_info "install dep ..."
   # 安装依赖软件
   command -v dnf > /dev/null && (sudo dnf install -y conntrack ipvsadm ipset jq iptables curl \
-    sysstat libseccomp > /dev/null && sudo /usr/sbin/modprobe ip_vs) || command -v yum && (sudo yum install -y conntrack ipvsadm ipset jq iptables curl \
+    sysstat libseccomp > /dev/null && sudo /usr/sbin/modprobe ip_vs) || command -v yum > /dev/null && (sudo yum install -y conntrack ipvsadm ipset jq iptables curl \
     sysstat libseccomp > /dev/null && sudo /usr/bin/env modprobe ip_vs) && return
 
-  command -v apt > /dev/null && sudo apt update > /dev/null && sudo apt install -y conntrack ipvsadm ipset jq iptables curl \
+  command -v apt > /dev/null && sudo apt update -qq && sudo apt install -y conntrack ipvsadm ipset jq iptables curl \
     sysstat libseccomp2 kmod > /dev/null && (sudo /usr/bin/env modprobe ip_vs)
 
 }
@@ -498,13 +548,8 @@ _k8s_install_systemd(){
   sudo systemctl daemon-reload
 }
 
-# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
-_containerd_config(){
-  _cni_install
-
-  sudo mkdir -p /etc/containerd/
-  sudo cp systemd/containerd/config.toml /etc/containerd/
-
+_cri_config(){
+  print_info "config cri ..."
   sudo rm -rf /etc/sysctl.d/99-kubernetes-cri.conf
   sudo touch /etc/sysctl.d/99-kubernetes-cri.conf
   echo "net.bridge.bridge-nf-call-iptables  = 1" | sudo tee -a /etc/sysctl.d/99-kubernetes-cri.conf > /dev/null
@@ -513,9 +558,135 @@ _containerd_config(){
 
   # cni conf
   sudo mkdir -p /opt/k8s/cni/net.d
-  sudo cp systemd/cni/10-flannel.conflist /opt/k8s/cni/net.d
+  sudo cp systemd/etc/cni/10-flannel.conflist /opt/k8s/cni/net.d
+}
+
+_crio_install(){
+  set +e
+  command -v crio > /dev/null
+  if [ $? -eq 0 ];then print_info "cri-o already install" ; return;fi
+  set -e
+
+  print_info "install cri-o ..."
+
+  local CRIO_VERSION_X=`echo $KUBERNETES_VERSION | cut -d "." -f 1`
+  local CRIO_VERSION_Y=`echo $KUBERNETES_VERSION | cut -d "." -f 2`
+  local CRIO_VERSION="$CRIO_VERSION_X"."$CRIO_VERSION_Y"
+
+  set -x
+
+  command -v dnf > /dev/null && isRPM=1
+  command -v yum > /dev/null && isRPM=1
+
+  test -n "$isRPM" && sudo yum install -y \
+  btrfs-progs-devel \
+  containers-common \
+  device-mapper-devel \
+  git \
+  glib2-devel \
+  glibc-devel \
+  glibc-static \
+  $(command -v go > /dev/null || echo "go") \
+  gpgme-devel \
+  libassuan-devel \
+  libgpg-error-devel \
+  libseccomp-devel \
+  libselinux-devel \
+  pkgconfig \
+  runc
+
+  # $(_sudo) sed -i "s#deb.debian.org#mirrors.ustc.edu.cn#g" /etc/apt/sources.list
+  # $(_sudo) sed -i "s#security.debian.org#mirrors.ustc.edu.cn#g" /etc/apt/sources.list
+  #
+  # $(_sudo) sed -i "s#archive.ubuntu.com#mirrors.ustc.edu.cn#g" /etc/apt/sources.list
+  # $(_sudo) sed -i "s#security.ubuntu.com#mirrors.ustc.edu.cn#g" /etc/apt/sources.list
+
+  command -v apt > /dev/null \
+  && $(_sudo) apt update -qq \
+  && $(_sudo) apt install -y software-properties-common \
+  && $(_sudo) apt-add-repository -y ppa:projectatomic/ppa \
+  && $(_sudo) apt-get update -qq && $(_sudo) apt-get install -y \
+  btrfs-tools \
+  containers-common \
+  git \
+  $(command -v go > /dev/null || echo "golang-go") \
+  libassuan-dev \
+  libdevmapper-dev \
+  libglib2.0-dev \
+  libc6-dev \
+  libgpgme11-dev \
+  libgpg-error-dev \
+  libseccomp-dev \
+  libsystemd-dev \
+  libselinux1-dev \
+  pkg-config \
+  $(command -v runc > /dev/null || echo "cri-o-runc") \
+  libudev-dev \
+  gcc
+
+  go_path=`go env GOPATH | cut -d ":" -f 1`
+
+  export GOPATH=$go_path
+
+  git clone --depth=1 -b release-${CRIO_VERSION} \
+    https://github.com/cri-o/cri-o \
+    $go_path/src/github.com/cri-o/cri-o || git clone --depth=1 -b master \
+        https://github.com/cri-o/cri-o \
+        $go_path/src/github.com/cri-o/cri-o
+
+  if ! [ -d $go_path/src/github.com/cri-o/cri-o ];then
+    exit 1
+  fi
+
+  cd $go_path/src/github.com/cri-o/cri-o
+
+  go version
+  $(_sudo) go version || true
+  go env
+  $(_sudo) go env || true
+  go get github.com/cpuguy83/go-md2man
+
+  make
+  # make build-static CONTAINER_RUNTIME=docker
+  $(_sudo) PATH=$GOPATH/bin:$PATH GOPATH=$go_path make install.bin
+  $(_sudo) PATH=$GOPATH/bin:$PATH GOPATH=$go_path make install.config
+  $(_sudo) PATH=$GOPATH/bin:$PATH GOPATH=$go_path make install.systemd
+
+  # command -v yum > /dev/null && sudo yum install cri-o
+  #
+  # command -v apt > /dev/null && (sudo apt-add-repository -y ppa:projectatomic/ppa \
+  #   && sudo apt-get update -qq \
+  #   && sudo apt-get install cri-o-$CRIO_VERSION)
+}
+
+_crio_config(){
+  _cni_install
+  _crio_install
+  print_info "config cri-o ..."
+  sudo mkdir -p /etc/crio/
+  # crio --config="" config --default > crio.conf
+  sudo cp systemd/etc/crio/crio.conf /etc/crio/
+
+  _cri_config
+
+  local CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/crio/crio.sock"
+
+  sudo sed -i "s#--container-runtime=docker#--container-runtime=remote#g" /etc/systemd/system/kubelet.service
+  sudo sed -i "s#--container-runtime-endpoint=unix:///var/run/dockershim.sock#--container-runtime-endpoint=${CONTAINER_RUNTIME_ENDPOINT}#g" /etc/systemd/system/kubelet.service
+}
+
+# https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
+_containerd_config(){
+  _cni_install
+  print_info "config containerd ..."
+  sudo mkdir -p /etc/containerd/
+  # containerd config default > /etc/containerd/config.toml
+  sudo cp systemd/etc/containerd/config.toml /etc/containerd/
+
+  _cri_config
 
   local CONTAINER_RUNTIME_ENDPOINT="unix:///run/containerd/containerd.sock"
+  # local CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/crio/crio.sock"
 
   sudo sed -i "s#--container-runtime=docker#--container-runtime=remote#g" /etc/systemd/system/kubelet.service
   sudo sed -i "s#--container-runtime-endpoint=unix:///var/run/dockershim.sock#--container-runtime-endpoint=${CONTAINER_RUNTIME_ENDPOINT}#g" /etc/systemd/system/kubelet.service
@@ -576,12 +747,20 @@ encryption-config.yaml} \
 
   _k8s_install_systemd
 
-  if ! [ "${1}" = "--containerd" ];then
-    print_info "Kubelet Runtime is Docker"
-    _k8s_install_systemd_docker
-  else
+  _gvisor_install
+
+  if [ "${1}" = "--containerd" ];then
     print_info "Kubelet Runtime is Containerd"
     _containerd_config
+    _gvisor_containerd_conf
+  elif [ "${1}" = "--crio" ];then
+    print_info "Kubelet Runtime is CRI-O"
+    _crio_config
+    _gvisor_crio_conf
+  else
+    print_info "Kubelet Runtime is Docker"
+    _gvisor_docker_conf
+    _k8s_install_systemd_docker
   fi
 
   sudo systemctl daemon-reload
@@ -658,7 +837,21 @@ kube-proxy.kubeconfig} \
       ${K8S_CONF_PATH:-/opt/bin/k8s/conf}/$file ; \
   done
 
-  _k8s_install_systemd_docker
+  _gvisor_install
+
+  if [ "${2}" = "--containerd" ];then
+    print_info "Kubelet Runtime is Containerd"
+    _containerd_config
+    _gvisor_containerd_conf
+  elif [ "${2}" = "--crio" ];then
+    print_info "Kubelet Runtime is CRI-O"
+    _crio_config
+    _gvisor_crio_conf
+  else
+    print_info "Kubelet Runtime is Docker"
+    _gvisor_docker_conf
+    _k8s_install_systemd_docker
+  fi
 
   _k8s_install_systemd ${HOSTNAME}
 
@@ -747,7 +940,7 @@ case $_command in
       _kubernetes_server_install $@
       ;;
     pull-k8s-image )
-      _pull_k8s_image $@
+      _get_kubernetes_server_by_docker_image $@
       ;;
     kubectl-install )
       kubectl_install
@@ -832,6 +1025,6 @@ case $_command in
     ;;
 
     * )
-    echo "command not found"
+    command -v $_command > /dev/null && $_command $@ || echo "command not found"
     ;;
 esac
